#pragma once

#include <Geode/Geode.hpp>
#include <array>

#ifndef GEODE_LIKELY
    #if defined(__GNUC__) || defined(__clang__)
        #define GEODE_LIKELY(x) __builtin_expect(!!(x), 1)
    #else
        #define GEODE_LIKELY(x) (x)
    #endif
#endif

struct PlayerState
{
    struct PlayerObjectMembers
    {
        bool m_wasTeleported;
        bool m_fixGravityBug;
        bool m_reverseSync;
        double m_yVelocityBeforeSlope;
        double m_dashX;
        double m_dashY;
        double m_dashAngle;
        double m_dashStartTime;
        DashRingObject *m_dashRing;
        double m_slopeStartTime;
        bool m_justPlacedStreak;
#if GEODE_COMP_GD_VERSION == 22074
        cocos2d::CCNode *m_maybeLastGroundObject;
#else
        GameObject *m_maybeLastGroundObject;
#endif
        int m_lastCollisionBottom;
        int m_lastCollisionTop;
        int m_lastCollisionLeft;
        int m_lastCollisionRight;
        int m_unk50C;
        int m_unk510;
        GameObject *m_currentSlope2;
        GameObject *m_preLastGroundObject;
        float m_slopeAngle;
        bool m_slopeSlidingMaybeRotated;
        bool m_quickCheckpointMode;
        GameObject *m_collidedObject;
        GameObject *m_lastGroundObject;
        GameObject *m_collidingWithLeft;
        GameObject *m_collidingWithRight;
        int m_maybeSavedPlayerFrame;
        double m_scaleXRelated2;
        double m_groundYVelocity;
        double m_yVelocityRelated;
        double m_scaleXRelated3;
        double m_scaleXRelated4;
        double m_scaleXRelated5;
        bool m_isCollidingWithSlope;
        bool m_isBallRotating;
        bool m_unk669;
        GameObject *m_currentPotentialSlope;
        GameObject *m_currentSlope;
        double unk_584;
        int m_collidingWithSlopeId;
        bool m_slopeFlipGravityRelated;
        float m_slopeAngleRadians;
        float m_rotationSpeed;
        float m_rotateSpeed;
        bool m_isRotating;
        bool m_isBallRotating2;
        bool m_hasGlow;
        bool m_isHidden;
        double m_speedMultiplier;
        double m_yStart;
        double m_gravity;
        float m_trailingParticleLife;
        float m_unk648;
        double m_gameModeChangedTime;
        bool m_padRingRelated;
        bool m_maybeReducedEffects;
        bool m_maybeIsFalling;
        bool m_shouldTryPlacingCheckpoint;
        bool m_playEffects;
        bool m_maybeCanRunIntoBlocks;
        bool m_hasGroundParticles;
        bool m_hasShipParticles;
        bool m_isOnGround3;
        bool m_checkpointTimeout;
        double m_lastCheckpointTime;
        double m_lastJumpTime;
        double m_lastFlipTime;
        double m_flashTime;
        float m_flashDuration;
        float m_flashDelay;
        double m_lastSpiderFlipTime;
        bool m_unkBool5;
        bool m_maybeIsVehicleGlowing;
        bool m_switchWaveTrailColor;
        bool m_practiceDeathEffect;
        double m_accelerationOrSpeed;
        double m_snapDistance;
        bool m_ringJumpRelated;
        GameObject *m_objectSnappedTo;
        int m_onFlyCheckpointTries;
        bool m_maybeSpriteRelated;
        bool m_useLandParticles0;
        float m_landParticlesAngle;
        float m_landParticleRelatedY;
        int m_playerStreak;
        float m_streakStrokeWidth;
        bool m_disableStreakTint;
        bool m_alwaysShowStreak;
        ShipStreak m_shipStreakType;
        double m_slopeRotation;
        double m_currentSlopeYVelocity;
        double m_unk3d0;
        double m_blackOrbRelated;
        bool m_unk3e0;
        bool m_unk3e1;
        bool m_isAccelerating;
        bool m_isCurrentSlopeTop;
        double m_collidedTopMinY;
        double m_collidedBottomMaxY;
        double m_collidedLeftMaxX;
        double m_collidedRightMinX;
        bool m_fadeOutStreak;
        bool m_canPlaceCheckpoint;
        bool m_maybeIsColliding;
        bool m_jumpBuffered;
        bool m_stateRingJump;
        bool m_wasJumpBuffered;
        bool m_wasRobotJump;
        unsigned char m_stateJumpBuffered;
        bool m_stateRingJump2;
        bool m_touchedRing;
        bool m_touchedCustomRing;
        bool m_touchedGravityPortal;
        bool m_maybeTouchedBreakableBlock;
        bool m_touchedPad;
        double m_yVelocity;
        double m_fallSpeed;
        bool m_isOnSlope;
        bool m_wasOnSlope;
        float m_slopeVelocity;
        bool m_maybeUpsideDownSlope;
        bool m_isShip;
        bool m_isBird;
        bool m_isBall;
        bool m_isDart;
        bool m_isRobot;
        bool m_isSpider;
        bool m_isUpsideDown;
        bool m_isDead;
        bool m_isOnGround;
        bool m_isGoingLeft;
        bool m_isSideways;
        bool m_isSwing;
        int m_reverseRelated;
        double m_maybeReverseSpeed;
        double m_maybeReverseAcceleration;
        float m_xVelocityRelated2;
        bool m_isDashing;
        int m_unk9e8;
        int m_groundObjectMaterial;
        float m_vehicleSize;
        float m_playerSpeed;
        cocos2d::CCPoint m_shipRotation;
        cocos2d::CCPoint m_lastPortalPos;
        float m_unkUnused3;
        bool m_isOnGround2;
        double m_lastLandTime;
        float m_platformerVelocityRelated;
        bool m_maybeIsBoosted;
        double m_scaleXRelatedTime;
        bool m_decreaseBoostSlide;
        bool m_unkA29;
        bool m_isLocked;
        bool m_controlsDisabled;
        cocos2d::CCPoint m_lastGroundedPos;
        GameObject *m_lastActivatedPortal;
        bool m_hasEverJumped;
        bool m_hasEverHitRing;
        cocos2d::CCPoint m_position;
        bool m_isSecondPlayer;
        bool m_unkA99;
        double m_totalTime;
        bool m_isBeingSpawnedByDualPortal;
        float m_audioScale;
        float m_unkAngle1;
        float m_yVelocityRelated3;
        bool m_defaultMiniIcon;
        bool m_swapColors;
        bool m_switchDashFireColor;
        int m_followRelated;
        float m_unk838;
        int m_stateOnGround;
        unsigned char m_stateUnk;
        unsigned char m_stateNoStickX;
        unsigned char m_stateNoStickY;
        unsigned char m_stateUnk2;
        int m_stateBoostX;
        int m_stateBoostY;
        int m_maybeStateForce2;
        int m_stateScale;
        double m_platformerXVelocity;
        bool m_holdingRight;
        bool m_holdingLeft;
        bool m_leftPressedFirst;
        double m_scaleXRelated;
        bool m_maybeHasStopped;
        float m_xVelocityRelated;
        bool m_maybeGoingCorrectSlopeDirection;
        bool m_isSliding;
        double m_maybeSlopeForce;
        bool m_isOnIce;
        double m_physDeltaRelated;
        bool m_isOnGround4;
        int m_maybeSlidingTime;
        double m_maybeSlidingStartTime;
        double m_changedDirectionsTime;
        double m_slopeEndTime;
        bool m_isMoving;
        bool m_platformerMovingLeft;
        bool m_platformerMovingRight;
        bool m_isSlidingRight;
        double m_maybeChangedDirectionAngle;
        double m_unkUnused2;
        bool m_isPlatformer;
        int m_stateNoAutoJump;
        int m_stateDartSlide;
        int m_stateHitHead;
        int m_stateFlipGravity;
        float m_gravityMod;
        int m_stateForce;
        cocos2d::CCPoint m_stateForceVector;
        bool m_affectedByForces;
        float m_somethingPlayerSpeedTime;
        float m_playerSpeedAC;
        bool m_fixRobotJump;
        bool m_inputsLocked;
        bool m_gv0123;
        int m_iconRequestID;
        int m_unkUnused;
        bool m_isOutOfBounds;
        float m_fallStartY;
        bool m_disablePlayerSqueeze;
        bool m_robotAnimation1Enabled;
        bool m_robotAnimation2Enabled;
        bool m_spiderAnimationEnabled;
        bool m_ignoreDamage;
        bool m_enable22Changes;
    };

    struct OBB2DMembers
    {
        std::array<cocos2d::CCPoint, 4> m_corners;
        std::array<cocos2d::CCPoint, 4> m_positions;
        std::array<cocos2d::CCPoint, 4> m_edges;
        std::array<double, 2> m_projections;
        cocos2d::CCPoint m_center;
    };

    struct GameObjectMembers
    {
        int m_someOtherIndex;
        int m_innerSectionIndex;
        int m_outerSectionIndex;
        int m_middleSectionIndex;
        bool m_hasExtendedCollision;
        cocos2d::ccColor3B m_groupColor;
        bool m_isColorSpriteBlack;
        bool m_isObjectBlack;
        float m_blackChildOpacity;
        bool m_blackChildOpacityLocked;
        bool m_editorEnabled;
        bool m_unk28c;
        int m_activeMainColorID;
        int m_activeDetailColorID;
        bool m_baseUsesHSV;
        bool m_detailUsesHSV;
        float m_positionXOffset;
        float m_positionYOffset;
        float m_rotationXOffset;
        float m_unk2A8;
        float m_rotationYOffset;
        float m_unk2B0;
        float m_scaleXOffset;
        float m_scaleYOffset;
        float m_unk2BC;
        float m_unk2C0;
        bool m_tempOffsetXRelated;
        bool m_isFlipX;
        bool m_isFlipY;
        cocos2d::CCPoint m_customBoxOffset;
        bool m_boxOffsetCalculated;
        cocos2d::CCPoint m_boxOffset;
        bool m_shouldUseOuterOb;
        bool m_isRingPoweredOn;
        float m_width;
        float m_height;
        bool m_addToNodeContainer;
        bool m_isActivated;
        bool m_isDisabled2;
        bool m_hasParticles;
        bool m_particleUseObjectColor;
        bool m_hasColorSprite;
        cocos2d::CCPoint m_particleOffset;
        bool m_isParticleSpriteLocked;
        cocos2d::CCRect m_textureRect;
        bool m_isDirty;
        bool m_isObjectPosDirty;
        bool m_isUnmodifiedPosDirty;
        float m_fadeMargin;
        cocos2d::CCRect m_objectRect;
        bool m_isObjectRectDirty;
        bool m_isOrientedBoxDirty;
        bool m_colorSpriteLocked;
        bool m_unk353;
        bool m_canRotateFree;
        bool m_isMirroredByScale;
        int m_linkedGroup;
        int m_unk35C;
        short m_colorType;
        short m_childColorType;
        bool m_shouldBlendBase;
        bool m_shouldBlendDetail;
        bool m_hasCustomChild;
        bool m_unk367;
        bool m_unk370;
        float m_objectRadius;
        bool m_isRotationAligned;
        float m_spriteWidthScale;
        float m_spriteHeightScale;
        int m_uniqueID;
        GameObjectType m_objectType;
        GameObjectType m_savedObjectType;
        int m_unk390;
        float m_unmodifiedPositionX;
        float m_unmodifiedPositionY;
        double m_positionX;
        double m_positionY;
        cocos2d::CCPoint m_startPosition;
        bool m_usesAudioScale;
        bool m_hasNoAudioScale;
        bool m_isDisabled;
        float m_startRotationX;
        float m_startRotationY;
        float m_startScaleX;
        float m_startScaleY;
        float m_customScaleX;
        float m_customScaleY;
        bool m_startFlipX;
        bool m_startFlipY;
        bool m_unk3ee;
        bool m_isInvisible;
        int m_unk3D8;
        short m_varianceIndex;
        bool m_unk3DE;
        short m_enterType;
        short m_exitType;
        short m_enterChannel;
        short m_objectMaterial;
        bool m_unk3E8;
        short m_parentMode;
        bool m_hasNoGlow;
        int m_targetColor;
        int m_objectID;
        bool m_unk3F8;
        bool m_intrinsicDontFade;
        bool m_ignoreEnter;
        bool m_ignoreFade;
        bool m_isSolidColorBlock;
        bool m_unk3FD;
        bool m_customSpriteColor;
        short m_customColorType;
        bool m_isDontEnter;
        bool m_isDontFade;
        bool m_hasNoEffects;
        bool m_hasNoParticles;
        int m_defaultZOrder;
        bool m_unk40C;
        bool m_colorZLayerRelated;
        bool m_customAudioScale;
        float m_minAudioScale;
        float m_maxAudioScale;
        bool m_particleLocked;
        int m_property53;
        bool m_isInvisibleBlock;
        bool m_customGlowColor;
        bool m_glowColorIsLBG;
        bool m_cantColorGlow;
        float m_opacityMod;
        bool m_slopeUphill;
        int m_slopeDirection;
        bool m_slopeIsHazard;
        float m_opacityMod2;
        bool m_baseOrDetailBlending;
        ZLayer m_defaultZLayer;
        bool m_zFixedZLayer;
        ZLayer m_zLayer;
        int m_zOrder;
        bool m_wasSelected;
        bool m_isSelected;
        float m_unk460;
        cocos2d::CCPoint m_unk464;
        bool m_updateParents;
        bool m_updateEditorColor;
        bool m_hasGroupParent;
        bool m_hasAreaParent;
        float m_scaleX;
        float m_scaleY;
        short m_editorLayer;
        short m_editorLayer2;
        int m_enabledGroupsCounter;
        bool m_updateCustomContentSize;
        bool m_hasContentSize;
        bool m_isNoTouch;
        cocos2d::CCSize m_lastSize;
        cocos2d::CCPoint m_lastPosition;
        int m_unk4C0;
        int m_unk4C4;
        int m_unk4C8;
        int m_unk4CC;
        GameObjectClassType m_classType;
        bool m_isTrigger;
        bool m_isSpawnOrderTrigger;
        bool m_isColorTrigger;
        bool m_dontIgnoreDuration;
        bool m_canBeControlled;
        bool m_activateTriggerInEditor;
        bool m_isStartPos;
        bool m_isHighDetail;
        bool m_unk4F8;
        bool m_isDecoration;
        bool m_isDecoration2;
        bool m_unk4fb;
        bool m_maybeNotColorable;
        bool m_isPassable;
        bool m_isHide;
        bool m_isNonStickX;
        bool m_isNonStickY;
        bool m_isIceBlock;
        bool m_isGripSlope;
        bool m_isScaleStick;
        bool m_isExtraSticky;
        bool m_isDontBoostY;
        bool m_isDontBoostX;
        bool m_unk507;
        bool m_unk508;
        float m_unk50C;
        float m_pixelScaleX;
        float m_pixelScaleY;
        int m_mainColorKeyIndex;
        int m_detailColorKeyIndex;
        uint8_t m_areaOpacityRelated;
        float m_areaOpacityValue;
        int m_areaOpacityIndex;
        int m_unk52C;
        bool m_unk530;
        bool m_isUIObject;
        bool m_greenDebugDraw;
    };

    PlayerObjectMembers plMembers;
    OBB2DMembers obbMembers;
    GameObjectMembers goMembers;

    static inline constexpr size_t OBBSize =
        offsetof(OBB2DMembers, m_center) + sizeof(cocos2d::CCPoint);

    cocos2d::CCPoint position;
    float rotation;
    float rotationX;
    float rotationY;
    float scaleX;
    float scaleY;

    inline void saveState(PlayerObject *player);
    inline void loadState(PlayerObject *player) const;
};

inline void PlayerState::saveState(PlayerObject *player)
{
    auto& p = *player;

    position = p.getPosition();
    rotation = p.getRotation();
    rotationX = p.getRotationX();
    rotationY = p.getRotationY();
    scaleX = p.getScaleX();
    scaleY = p.getScaleY();

    if (auto* obb = p.m_orientedBox; GEODE_LIKELY(obb))
        obbMembers.m_corners = obb->m_corners;

    plMembers.m_wasTeleported = p.m_wasTeleported;
    plMembers.m_fixGravityBug = p.m_fixGravityBug;
    plMembers.m_reverseSync = p.m_reverseSync;
    plMembers.m_yVelocityBeforeSlope = p.m_yVelocityBeforeSlope;
    plMembers.m_dashX = p.m_dashX;
    plMembers.m_dashY = p.m_dashY;
    plMembers.m_dashAngle = p.m_dashAngle;
    plMembers.m_dashStartTime = p.m_dashStartTime;
    plMembers.m_slopeStartTime = p.m_slopeStartTime;
    plMembers.m_slopeAngle = p.m_slopeAngle;
    plMembers.m_slopeSlidingMaybeRotated = p.m_slopeSlidingMaybeRotated;
    plMembers.m_maybeSavedPlayerFrame = p.m_maybeSavedPlayerFrame;
    plMembers.m_scaleXRelated2 = p.m_scaleXRelated2;
    plMembers.m_scaleXRelated3 = p.m_scaleXRelated3;
    plMembers.m_scaleXRelated4 = p.m_scaleXRelated4;
    plMembers.m_scaleXRelated5 = p.m_scaleXRelated5;
    plMembers.m_yVelocityRelated = p.m_yVelocityRelated;
    plMembers.m_slopeAngleRadians = p.m_slopeAngleRadians;
    plMembers.m_rotationSpeed = p.m_rotationSpeed;
    plMembers.m_rotateSpeed = p.m_rotateSpeed;
    plMembers.m_isRotating = p.m_isRotating;
    plMembers.m_speedMultiplier = p.m_speedMultiplier;
    plMembers.m_yStart = p.m_yStart;
    plMembers.m_gameModeChangedTime = p.m_gameModeChangedTime;
    plMembers.m_accelerationOrSpeed = p.m_accelerationOrSpeed;
    plMembers.m_snapDistance = p.m_snapDistance;
    plMembers.m_xVelocityRelated2 = p.m_xVelocityRelated2;
    plMembers.m_fallSpeed = p.m_fallSpeed;
    plMembers.m_slopeVelocity = p.m_slopeVelocity;
    plMembers.m_currentSlopeYVelocity = p.m_currentSlopeYVelocity;
    plMembers.m_xVelocityRelated = p.m_xVelocityRelated;
    plMembers.m_physDeltaRelated = p.m_physDeltaRelated;
    plMembers.m_maybeSlopeForce = p.m_maybeSlopeForce;
    plMembers.m_maybeChangedDirectionAngle = p.m_maybeChangedDirectionAngle;
    plMembers.m_changedDirectionsTime = p.m_changedDirectionsTime;
    plMembers.m_slopeEndTime = p.m_slopeEndTime;
    plMembers.m_isPlatformer = p.m_isPlatformer;
    plMembers.m_isUpsideDown = p.m_isUpsideDown;
    plMembers.m_isGoingLeft = p.m_isGoingLeft;
    plMembers.m_isSideways = p.m_isSideways;
    plMembers.m_reverseRelated = p.m_reverseRelated;
    plMembers.m_maybeReverseSpeed = p.m_maybeReverseSpeed;
    plMembers.m_maybeReverseAcceleration = p.m_maybeReverseAcceleration;
    plMembers.m_isDashing = p.m_isDashing;
    plMembers.m_vehicleSize = p.m_vehicleSize;
    plMembers.m_playerSpeed = p.m_playerSpeed;
    plMembers.m_platformerVelocityRelated = p.m_platformerVelocityRelated;
    plMembers.m_slopeFlipGravityRelated = p.m_slopeFlipGravityRelated;
    plMembers.m_stateFlipGravity = p.m_stateFlipGravity;
    plMembers.m_platformerXVelocity = p.m_platformerXVelocity;
    plMembers.m_touchedGravityPortal = p.m_touchedGravityPortal;
}

inline void PlayerState::loadState(PlayerObject *player) const
{
    auto& p = *player;

    p.setPosition(position);
    p.setRotation(rotation);
    p.setRotationX(rotationX);
    p.setRotationY(rotationY);
    p.setScaleX(scaleX);
    p.setScaleY(scaleY);

    if (auto* obb = p.m_orientedBox; GEODE_LIKELY(obb))
        obb->m_corners = obbMembers.m_corners;

    p.m_wasTeleported = plMembers.m_wasTeleported;
    p.m_fixGravityBug = plMembers.m_fixGravityBug;
    p.m_reverseSync = plMembers.m_reverseSync;
    p.m_yVelocityBeforeSlope = plMembers.m_yVelocityBeforeSlope;
    p.m_dashX = plMembers.m_dashX;
    p.m_dashY = plMembers.m_dashY;
    p.m_dashAngle = plMembers.m_dashAngle;
    p.m_dashStartTime = plMembers.m_dashStartTime;
    p.m_slopeStartTime = plMembers.m_slopeStartTime;
    p.m_slopeAngle = plMembers.m_slopeAngle;
    p.m_slopeSlidingMaybeRotated = plMembers.m_slopeSlidingMaybeRotated;
    p.m_maybeSavedPlayerFrame = plMembers.m_maybeSavedPlayerFrame;
    p.m_scaleXRelated2 = plMembers.m_scaleXRelated2;
    p.m_scaleXRelated3 = plMembers.m_scaleXRelated3;
    p.m_scaleXRelated4 = plMembers.m_scaleXRelated4;
    p.m_scaleXRelated5 = plMembers.m_scaleXRelated5;
    p.m_yVelocityRelated = plMembers.m_yVelocityRelated;
    p.m_slopeAngleRadians = plMembers.m_slopeAngleRadians;
    p.m_rotationSpeed = plMembers.m_rotationSpeed;
    p.m_rotateSpeed = plMembers.m_rotateSpeed;
    p.m_isRotating = plMembers.m_isRotating;
    p.m_speedMultiplier = plMembers.m_speedMultiplier;
    p.m_yStart = plMembers.m_yStart;
    p.m_gameModeChangedTime = plMembers.m_gameModeChangedTime;
    p.m_accelerationOrSpeed = plMembers.m_accelerationOrSpeed;
    p.m_snapDistance = plMembers.m_snapDistance;
    p.m_xVelocityRelated2 = plMembers.m_xVelocityRelated2;
    p.m_fallSpeed = plMembers.m_fallSpeed;
    p.m_slopeVelocity = plMembers.m_slopeVelocity;
    p.m_currentSlopeYVelocity = plMembers.m_currentSlopeYVelocity;
    p.m_xVelocityRelated = plMembers.m_xVelocityRelated;
    p.m_physDeltaRelated = plMembers.m_physDeltaRelated;
    p.m_maybeSlopeForce = plMembers.m_maybeSlopeForce;
    p.m_maybeChangedDirectionAngle = plMembers.m_maybeChangedDirectionAngle;
    p.m_changedDirectionsTime = plMembers.m_changedDirectionsTime;
    p.m_slopeEndTime = plMembers.m_slopeEndTime;
    p.m_isPlatformer = plMembers.m_isPlatformer;
    p.m_isUpsideDown = plMembers.m_isUpsideDown;
    p.m_isGoingLeft = plMembers.m_isGoingLeft;
    p.m_isSideways = plMembers.m_isSideways;
    p.m_reverseRelated = plMembers.m_reverseRelated;
    p.m_maybeReverseSpeed = plMembers.m_maybeReverseSpeed;
    p.m_maybeReverseAcceleration = plMembers.m_maybeReverseAcceleration;
    p.m_isDashing = plMembers.m_isDashing;
    p.m_vehicleSize = plMembers.m_vehicleSize;
    p.m_playerSpeed = plMembers.m_playerSpeed;
    p.m_platformerVelocityRelated = plMembers.m_platformerVelocityRelated;
    p.m_slopeFlipGravityRelated = plMembers.m_slopeFlipGravityRelated;
    p.m_stateFlipGravity = plMembers.m_stateFlipGravity;
    p.m_platformerXVelocity = plMembers.m_platformerXVelocity;
    p.m_touchedGravityPortal = plMembers.m_touchedGravityPortal;
}
